apiVersion: authentication.keycloak.upbound.io/v1alpha1
kind: Bindings
metadata:
  annotations:
    meta.upbound.io/example-id: authentication/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: browser_authentication_binding
  name: browser-authentication-binding
spec:
  forProvider:
    browserFlow: my-flow-alias
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: authentication.keycloak.upbound.io/v1alpha1
kind: Execution
metadata:
  annotations:
    meta.upbound.io/example-id: authentication/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: execution_one
  name: execution-one
spec:
  forProvider:
    authenticator: auth-cookie
    parentFlowAlias: my-flow-alias
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    requirement: ALTERNATIVE

---

apiVersion: authentication.keycloak.upbound.io/v1alpha1
kind: Execution
metadata:
  annotations:
    meta.upbound.io/example-id: authentication/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: execution_two
  name: execution-two
spec:
  forProvider:
    authenticator: identity-provider-redirector
    parentFlowAlias: my-flow-alias
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    requirement: ALTERNATIVE

---

apiVersion: authentication.keycloak.upbound.io/v1alpha1
kind: Flow
metadata:
  annotations:
    meta.upbound.io/example-id: authentication/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: flow
  name: flow
spec:
  forProvider:
    alias: my-flow-alias
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.upbound.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: authentication/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
