apiVersion: openidclient.keycloak.upbound.io/v1alpha1
kind: ClientServiceAccountRealmRole
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: client_service_account_role
  name: client-service-account-role
spec:
  forProvider:
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    role: ${keycloak_role.realm_role.name}
    serviceAccountUserClientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client

---

apiVersion: openidclient.keycloak.upbound.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: client
  name: client
spec:
  forProvider:
    name: client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: realm.keycloak.upbound.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openidclient/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
